apiVersion: v1
kind: Pod
metadata:
  annotations:
    cpus: "1"
    id: i-057cb20f
    image: ubuntu:16.04.4-server-amd64
    mac: 06:fe:05:7c:b2:0f
    memory_mb: "1024"
  labels:
    app: ranchervm
    name: rke-02
    role: vm
    unique_name: rke-02-37768226
  name: rke-02-37768226
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: ranchervm
            name: rke-02
            role: vm
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - /usr/bin/startvm
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: IFACE
      value: ens33
    - name: MEMORY_MB
      value: "1024"
    - name: CPUS
      value: "1"
    - name: MAC
      value: 06:fe:05:7c:b2:0f
    - name: INSTANCE_ID
      value: i-057cb20f
    - name: MIGRATE
      value: "false"
    - name: MY_VM_NAME
      value: rke-02
    - name: PUBLIC_KEY_COUNT
      value: "1"
    - name: PUBLIC_KEY_1
      value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0JXJ5BmKNHLDQGDK0SpyeNbl+DOaKcVLE/yoNl6YxMxehQ36HxudmyPWV0jk7hMkrLugklGtcyQZFtp/A9YWSycarfHE89B6IYxbDPir3NTChGtMIzc3MvxrBPNmKTo3MKqZyB+ZRmyvy+F5OoKS9P4Tk9guBuRnseyNvq2bfoekang+hlWw6ksgwtKsiTJjSrW9+96Z/0KNNcD3eDUexQIyuALWz0fYAvNZAfZXgd0GJ63OiwJ3nTcoWAso2NmRR5WSTjlV85ZmEUPWExLBrxVmx/JvDFI+V6PpYIbtY3gTzpqUNK3hqN9yS8ZQc7dngZWc6VFwA5tFFGAChs1TJ
        joliver@Jamess-MacBook-Pro.local
    image: rancher/vm-ubuntu:16.04.4-server-amd64
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - '[ -S /vm/${MY_POD_NAME}_vnc.sock ]'
    name: vm
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - '[ -S /vm/${MY_POD_NAME}_vnc.sock ]'
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /image
      name: vm-image
    - mountPath: /dev/kvm
      name: dev-kvm
    - mountPath: /vm
      name: vm-socket
    - mountPath: /bin
      name: vm-fs
      readOnly: true
      subPath: bin
    - mountPath: /etc
      name: vm-fs
      subPath: etc
    - mountPath: /lib
      name: vm-fs
      readOnly: true
      subPath: lib
    - mountPath: /lib64
      name: vm-fs
      readOnly: true
      subPath: lib64
    - mountPath: /sbin
      name: vm-fs
      readOnly: true
      subPath: sbin
    - mountPath: /usr
      name: vm-fs
      readOnly: true
      subPath: usr
    - mountPath: /var
      name: vm-fs
      readOnly: true
      subPath: var
  hostNetwork: true
  initContainers:
  - image: rancher/vm-tools
    imagePullPolicy: Always
    name: debootstrap
    volumeMounts:
    - mountPath: /vm-tools
      name: vm-fs
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /var/lib/rancher/vm/rke-02/vm-fs
      type: ""
    name: vm-fs
  - hostPath:
      path: /var/lib/rancher/vm/rke-02/vm-image
      type: ""
    name: vm-image
  - hostPath:
      path: /var/lib/rancher/vm/rke-02
      type: ""
    name: vm-socket
  - hostPath:
      path: /dev/kvm
      type: ""
    name: dev-kvm
---
apiVersion: v1
kind: Service
metadata:
  name: rke-02-novnc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: novnc
    port: 6080
    protocol: TCP
    targetPort: 6080
  selector:
    app: ranchervm
    name: rke-02
    role: novnc
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ranchervm
    name: rke-02
    role: novnc
  name: rke-02-novnc
  namespace: default
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: ranchervm
            name: rke-02
            role: vm
            unique_name: rke-02-37768226
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - novnc
    env:
    - name: VM_POD_NAME
      value: rke-02-37768226
    image: rancher/novnc
    imagePullPolicy: Always
    name: novnc
    volumeMounts:
    - mountPath: /vm
      name: vm-socket
    - mountPath: /podinfo
      name: podinfo
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /var/lib/rancher/vm/rke-02
      type: ""
    name: vm-socket
  - downwardAPI:
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
    name: podinfo
